sonar.projectKey=brayan-chiquito_nomisalud-back-end
sonar.organization=brayan-chiquito

sonar.projectName=NomiSalud Back-End
sonar.projectVersion=1.0

# Código fuente
sonar.sources=app
sonar.tests=tests
sonar.language=py
sonar.python.version=3.11

# Cobertura (generado por pytest-cov)
sonar.python.coverage.reportPaths=coverage.xml

# Exclusiones del análisis
sonar.exclusions=alembic/**,**/__pycache__/**,**/*.pyc

# Encoding
sonar.sourceEncoding=UTF-8
